# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98b25fc63ce2b03777a5c9c83183035de9988a3638610943a868f272befe03ab1765dffdcf698e99db29c5e12be089ac0be4b709e87f059f7277bbbf64e1abae

test:
  secret_key_base: 3344308230676238d2ecbb4590916c6fd400ff3ba8061c15e617803c5e9a5315729460fea215d4bd4723094fb3f02e29ae1a31f27a2ce8c74bc716faa01cf6bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
#
# Engine Yard says to store configuration settings like this in shared storage, like the production
# database.  But you can't do that because when this file is processed you can't yet make a
# connection to the production database.  Generating it on each start is not ideal since it will
# change, so this could be better.
production:
  secret_key_base: <%= require 'securerandom'; SecureRandom.hex(64) %>
